export { default as fillGrid } from './fill-grid'
export { default as shuffle } from './shuffle'
export { default as identifySquare } from './identify-square'
export { default as isSquare } from './sqare'
export * from './is-in'
